//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuleymaniyeTakvimi.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuleymaniyeTakvimi.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açı.
        /// </summary>
        internal static string Aci {
            get {
                return ResourceManager.GetString("Aci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akşam.
        /// </summary>
        internal static string Aksam {
            get {
                return ResourceManager.GetString("Aksam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Sesi.
        /// </summary>
        internal static string AlarmSound {
            get {
                return ResourceManager.GetString("AlarmSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm çal.
        /// </summary>
        internal static string AlarmSwitch {
            get {
                return ResourceManager.GetString("AlarmSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 dakika önceden.
        /// </summary>
        internal static string BesDakikaOnceden {
            get {
                return ResourceManager.GetString("BesDakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildiri Ayarı Devre Dışı.
        /// </summary>
        internal static string BildiriDevreDisiBaslik {
            get {
                return ResourceManager.GetString("BildiriDevreDisiBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to için bildiri devre dışı bırakıldı..
        /// </summary>
        internal static string BildiriDevreDisiIcerik {
            get {
                return ResourceManager.GetString("BildiriDevreDisiIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildiri Ayarı Etkinleşti.
        /// </summary>
        internal static string BildiriEtkinBaslik {
            get {
                return ResourceManager.GetString("BildiriEtkinBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to için bildiri etkinleştirildi..
        /// </summary>
        internal static string BildiriEtkinIcerik {
            get {
                return ResourceManager.GetString("BildiriEtkinIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim Göster.
        /// </summary>
        internal static string BildirimGosterSwitch {
            get {
                return ResourceManager.GetString("BildirimGosterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatırlatma Zamanı:.
        /// </summary>
        internal static string BildirmeZamani {
            get {
                return ResourceManager.GetString("BildirmeZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boylam: {0:G7}.
        /// </summary>
        internal static string Boylam {
            get {
                return ResourceManager.GetString("Boylam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boylam.
        /// </summary>
        internal static string BoylamFormatsiz {
            get {
                return ResourceManager.GetString("BoylamFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalar Saat.
        /// </summary>
        internal static string CalarSaat {
            get {
                return ResourceManager.GetString("CalarSaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Desteklemiyor.
        /// </summary>
        internal static string CihazDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlem: {0:G7}.
        /// </summary>
        internal static string Enlem {
            get {
                return ResourceManager.GetString("Enlem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlem.
        /// </summary>
        internal static string EnlemFormatsiz {
            get {
                return ResourceManager.GetString("EnlemFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinleştir.
        /// </summary>
        internal static string EtkinlestirSwitch {
            get {
                return ResourceManager.GetString("EtkinlestirSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezan Sesi.
        /// </summary>
        internal static string EzanSesi {
            get {
                return ResourceManager.GetString("EzanSesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecr-i Kâzip.
        /// </summary>
        internal static string FecriKazip {
            get {
                return ResourceManager.GetString("FecriKazip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecr-i Sâdık.
        /// </summary>
        internal static string FecriSadik {
            get {
                return ResourceManager.GetString("FecriSadik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radyo Fıtrat - Fıtrat&apos;ın Sesi.
        /// </summary>
        internal static string FitratinSesi {
            get {
                return ResourceManager.GetString("FitratinSesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        internal static string Hakkinda {
            get {
                return ResourceManager.GetString("Hakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haritada Göster.
        /// </summary>
        internal static string HaritadaGoster {
            get {
                return ResourceManager.GetString("HaritadaGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haritayı açarken bir sorun oluştu.\nDetaylar:.
        /// </summary>
        internal static string HaritaHatasi {
            get {
                return ResourceManager.GetString("HaritaHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horoz Ötüşü.
        /// </summary>
        internal static string HorozOtusu {
            get {
                return ResourceManager.GetString("HorozOtusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik yükleniyor ....
        /// </summary>
        internal static string IcerikYukleniyor {
            get {
                return ResourceManager.GetString("IcerikYukleniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkindi.
        /// </summary>
        internal static string Ikindi {
            get {
                return ResourceManager.GetString("Ikindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string Kapat {
            get {
                return ResourceManager.GetString("Kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıble.
        /// </summary>
        internal static string Kible {
            get {
                return ResourceManager.GetString("Kible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıble Göstergesi.
        /// </summary>
        internal static string KibleGostergesi {
            get {
                return ResourceManager.GetString("KibleGostergesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konuma erişmeye çalışırken bir sorun oluştu..
        /// </summary>
        internal static string KonumHatasi {
            get {
                return ResourceManager.GetString("KonumHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konuma Erişme İzni Yok.
        /// </summary>
        internal static string KonumIzniBaslik {
            get {
                return ResourceManager.GetString("KonumIzniBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamanın normal çalışması için Konuma erişme yetkisi vermeniz lazım!.
        /// </summary>
        internal static string KonumIzniIcerik {
            get {
                return ResourceManager.GetString("KonumIzniIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazda konum hizmetleri etkin değil. Önce konum hizmetlerini açmanız lazım!.
        /// </summary>
        internal static string KonumKapali {
            get {
                return ResourceManager.GetString("KonumKapali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum Hizmetleri Kapalı.
        /// </summary>
        internal static string KonumKapaliBaslik {
            get {
                return ResourceManager.GetString("KonumKapaliBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        internal static string KonumYenileButton {
            get {
                return ResourceManager.GetString("KonumYenileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum ve vakitler başarıyla yenilendi.
        /// </summary>
        internal static string KonumYenilendi {
            get {
                return ResourceManager.GetString("KonumYenilendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuş Cıvıltısı.
        /// </summary>
        internal static string KusCiviltisi {
            get {
                return ResourceManager.GetString("KusCiviltisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://suleymaniyetakvimi.com/Include/NamazVakitleri.htm.
        /// </summary>
        internal static string NamazVaktiAciklama {
            get {
                return ResourceManager.GetString("NamazVaktiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğle.
        /// </summary>
        internal static string Ogle {
            get {
                return ResourceManager.GetString("Ogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 dakika önceden.
        /// </summary>
        internal static string OnBesDakikaOnceden {
            get {
                return ResourceManager.GetString("OnBesDakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süleymaniye Vakfı Takvimi.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radyo.
        /// </summary>
        internal static string Radyo {
            get {
                return ResourceManager.GetString("Radyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radyo oynatmak için internet gerekli, lütfen internetin bağlı olduğunu kontrol edin, yada &apos;Web Sayfa&apos; linkine tıklayarak web syfasından dinleyebilirsiniz..
        /// </summary>
        internal static string RadyoIcinInternet {
            get {
                return ResourceManager.GetString("RadyoIcinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat Bölgesi: GMT {0}.
        /// </summary>
        internal static string SaatBolgesi {
            get {
                return ResourceManager.GetString("SaatBolgesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabah Sonu.
        /// </summary>
        internal static string SabahSonu {
            get {
                return ResourceManager.GetString("SabahSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        internal static string Sehir {
            get {
                return ResourceManager.GetString("Sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Testi.
        /// </summary>
        internal static string SesTesti {
            get {
                return ResourceManager.GetString("SesTesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir Sorunla Karşılaştık.
        /// </summary>
        internal static string SorunCikti {
            get {
                return ResourceManager.GetString("SorunCikti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal medya bağlantılarımız.
        /// </summary>
        internal static string SosyalMedyaBaglantisi {
            get {
                return ResourceManager.GetString("SosyalMedyaBaglantisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süleymaniye Vakfı.
        /// </summary>
        internal static string SuleymaniyeVakfi {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süleymaniye Vakfı Takvimi.
        /// </summary>
        internal static string SuleymaniyeVakfiTakvimi {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiTakvimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim.
        /// </summary>
        internal static string Takvim {
            get {
                return ResourceManager.GetString("Takvim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namaz vakitlerini yenilemek için internete bağlı olmanız gerekiyor, WiFi yada Mobil veriyi açın ve &apos;YENİLE&apos; yi tıklayın..
        /// </summary>
        internal static string TakvimIcinInternet {
            get {
                return ResourceManager.GetString("TakvimIcinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet Gerekiyor.
        /// </summary>
        internal static string TakvimIcinInternetBaslik {
            get {
                return ResourceManager.GetString("TakvimIcinInternetBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        internal static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testi Durdur.
        /// </summary>
        internal static string TestiDurdur {
            get {
                return ResourceManager.GetString("TestiDurdur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazınız Titretmeyi Desteklemiyor..
        /// </summary>
        internal static string TitremeyiDesteklemiyor {
            get {
                return ResourceManager.GetString("TitremeyiDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titret.
        /// </summary>
        internal static string TitresimSwitch {
            get {
                return ResourceManager.GetString("TitresimSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakti:.
        /// </summary>
        internal static string Vakti {
            get {
                return ResourceManager.GetString("Vakti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakti Hatırlatması.
        /// </summary>
        internal static string VaktiHatirlatmasi {
            get {
                return ResourceManager.GetString("VaktiHatirlatmasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Web Sayfa.
        /// </summary>
        internal static string WebSayfa {
            get {
                return ResourceManager.GetString("WebSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatsı.
        /// </summary>
        internal static string Yatsi {
            get {
                return ResourceManager.GetString("Yatsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatsı Sonu.
        /// </summary>
        internal static string YatsiSonu {
            get {
                return ResourceManager.GetString("YatsiSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Yayın Akışı.
        /// </summary>
        internal static string YayinAkisi {
            get {
                return ResourceManager.GetString("YayinAkisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükseklik: {0}.
        /// </summary>
        internal static string Yukseklik {
            get {
                return ResourceManager.GetString("Yukseklik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükseklik.
        /// </summary>
        internal static string YukseklikFormatsiz {
            get {
                return ResourceManager.GetString("YukseklikFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamanında.
        /// </summary>
        internal static string Zamaninda {
            get {
                return ResourceManager.GetString("Zamaninda", resourceCulture);
            }
        }
    }
}
