//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuleymaniyeTakvimi.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuleymaniyeTakvimi.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string Aci {
            get {
                return ResourceManager.GetString("Aci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who are submissive to God and stand up to all difficulties for His cause are named “Muslim”. Another pertinent characteristic of those who are “Muslim” is that they apply the commandments of God into their lives without any additions to it from their own desires. “Who speaks in a finer way than the one who invokes God, does righteous deeds and says: ‘I am of those who submit themselves to God (i.e. a Muslim)’?” (Fussilat 41:33)
        ///This application is designed to provide safe and fast access to prayer a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AciklamaBas {
            get {
                return ResourceManager.GetString("AciklamaBas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer Times From The Equator To The Poles.
        /// </summary>
        public static string AciklamaLinkText {
            get {
                return ResourceManager.GetString("AciklamaLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.islamandquran.org/research/prayer-times-from-the-equator-to-the-poles.html.
        /// </summary>
        public static string AciklamaLinkURL {
            get {
                return ResourceManager.GetString("AciklamaLinkURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  should be read..
        /// </summary>
        public static string AciklamaSon {
            get {
                return ResourceManager.GetString("AciklamaSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string AcikTema {
            get {
                return ResourceManager.GetString("AcikTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maghrib.
        /// </summary>
        public static string Aksam {
            get {
                return ResourceManager.GetString("Aksam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Maghrib: .
        /// </summary>
        public static string Aksamincikmasnakalanvakit {
            get {
                return ResourceManager.GetString("Aksamincikmasnakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occurred while the alarm plays. Details.
        /// </summary>
        public static string AlarmHatasi {
            get {
                return ResourceManager.GetString("AlarmHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string Alarmi {
            get {
                return ResourceManager.GetString("Alarmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting the alarm.
        /// </summary>
        public static string Alarmkurarkenhataolustu {
            get {
                return ResourceManager.GetString("Alarmkurarkenhataolustu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Ringtone.
        /// </summary>
        public static string AlarmSound {
            get {
                return ResourceManager.GetString("AlarmSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm duration: .
        /// </summary>
        public static string AlarmSuresi {
            get {
                return ResourceManager.GetString("AlarmSuresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the alarm.
        /// </summary>
        public static string AlarmSwitch {
            get {
                return ResourceManager.GetString("AlarmSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm ringtone repeats: .
        /// </summary>
        public static string AlarmTekrarlari {
            get {
                return ResourceManager.GetString("AlarmTekrarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Calendar.
        /// </summary>
        public static string AylikTakvim {
            get {
                return ResourceManager.GetString("AylikTakvim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access the Monthly Calendar. Please check that you are connected to the internet and your location service is active!.
        /// </summary>
        public static string AylikTakvimeErisemedi {
            get {
                return ResourceManager.GetString("AylikTakvimeErisemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Calendar Refreshed Successfully.
        /// </summary>
        public static string AylikTakvimYenilendi {
            get {
                return ResourceManager.GetString("AylikTakvimYenilendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijani.
        /// </summary>
        public static string Azerbaijani {
            get {
                return ResourceManager.GetString("Azerbaijani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes before.
        /// </summary>
        public static string BesDakikaOnceden {
            get {
                return ResourceManager.GetString("BesDakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications Disabled.
        /// </summary>
        public static string BildiriDevreDisiBaslik {
            get {
                return ResourceManager.GetString("BildiriDevreDisiBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  prayer notification disabled..
        /// </summary>
        public static string BildiriDevreDisiIcerik {
            get {
                return ResourceManager.GetString("BildiriDevreDisiIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications Enabled.
        /// </summary>
        public static string BildiriEtkinBaslik {
            get {
                return ResourceManager.GetString("BildiriEtkinBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  prayer notification enabled..
        /// </summary>
        public static string BildiriEtkinIcerik {
            get {
                return ResourceManager.GetString("BildiriEtkinIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification.
        /// </summary>
        public static string BildirimGosterSwitch {
            get {
                return ResourceManager.GetString("BildirimGosterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sticky notifications.
        /// </summary>
        public static string BildirimKapatma {
            get {
                return ResourceManager.GetString("BildirimKapatma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show prayer times in notification.
        /// </summary>
        public static string BildirimNamazVakitleri {
            get {
                return ResourceManager.GetString("BildirimNamazVakitleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: It may take half a minute to take effect.
        /// </summary>
        public static string BildirimNamazVakitleriUyari {
            get {
                return ResourceManager.GetString("BildirimNamazVakitleriUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend that you do not turn this setting off. If you turn it off, alarms may not ring on time. If your alarms do not ring, please check the application settings: In the &quot;Other permissions&quot; section, check that the &quot;Start in the Background&quot; option is selected. Make sure that the &quot;No Restrictions&quot; setting in the &quot;Battery saving&quot; section is on. To check these permissions now, click the button below..
        /// </summary>
        public static string BildirimUyari {
            get {
                return ResourceManager.GetString("BildirimUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Time: .
        /// </summary>
        public static string BildirmeZamani {
            get {
                return ResourceManager.GetString("BildirmeZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a ringtone.
        /// </summary>
        public static string Birsessecin {
            get {
                return ResourceManager.GetString("Birsessecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string BoylamFormatsiz {
            get {
                return ResourceManager.GetString("BoylamFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Prayer Times.
        /// </summary>
        public static string BugunkuNamazVakitleri {
            get {
                return ResourceManager.GetString("BugunkuNamazVakitleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Clock.
        /// </summary>
        public static string CalarSaat {
            get {
                return ResourceManager.GetString("CalarSaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support GPS.
        /// </summary>
        public static string CihazGPSDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazGPSDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support compass.
        /// </summary>
        public static string CihazPusulaDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazPusulaDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support vibration.
        /// </summary>
        public static string CihazTitretmeyiDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazTitretmeyiDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes.
        /// </summary>
        public static string Dakika {
            get {
                return ResourceManager.GetString("Dakika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes before.
        /// </summary>
        public static string DakikaOnceden {
            get {
                return ResourceManager.GetString("DakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Deutsch {
            get {
                return ResourceManager.GetString("Deutsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string EnlemFormatsiz {
            get {
                return ResourceManager.GetString("EnlemFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string EtkinlestirSwitch {
            get {
                return ResourceManager.GetString("EtkinlestirSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the alarm, vibration, and notification features for this prayer time.
        /// </summary>
        public static string EtkinlestirSwitchAciklama {
            get {
                return ResourceManager.GetString("EtkinlestirSwitchAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adhan.
        /// </summary>
        public static string EzanSesi {
            get {
                return ResourceManager.GetString("EzanSesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi.
        /// </summary>
        public static string Farsi {
            get {
                return ResourceManager.GetString("Farsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time for False Fajr (the beginning of Suhoor): .
        /// </summary>
        public static string FecriKazibingirmesinekalanvakit {
            get {
                return ResourceManager.GetString("FecriKazibingirmesinekalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Fajr (Sahar &amp; Suhoor time).
        /// </summary>
        public static string FecriKazip {
            get {
                return ResourceManager.GetString("FecriKazip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajr.
        /// </summary>
        public static string FecriSadik {
            get {
                return ResourceManager.GetString("FecriSadik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time for Fajr (the end of Suhoor): .
        /// </summary>
        public static string FecriSadikakalanvakit {
            get {
                return ResourceManager.GetString("FecriSadikakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat - The Voice of Fitrah.
        /// </summary>
        public static string FitratinSesi {
            get {
                return ResourceManager.GetString("FitratinSesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitrat TV.
        /// </summary>
        public static string FitratTV {
            get {
                return ResourceManager.GetString("FitratTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitrat TV Facebook Page.
        /// </summary>
        public static string FitratTVFacebook {
            get {
                return ResourceManager.GetString("FitratTVFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitrat TV Twitter Page.
        /// </summary>
        public static string FitratTVTwitter {
            get {
                return ResourceManager.GetString("FitratTVTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitrat TV Youtube Channel.
        /// </summary>
        public static string FitratTVYoutube {
            get {
                return ResourceManager.GetString("FitratTVYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        public static string GotoSettings {
            get {
                return ResourceManager.GetString("GotoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Hakkinda {
            get {
                return ResourceManager.GetString("Hakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Location On Map.
        /// </summary>
        public static string HaritadaGoster {
            get {
                return ResourceManager.GetString("HaritadaGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occurred while opening the map.\nDetails:.
        /// </summary>
        public static string HaritaHatasi {
            get {
                return ResourceManager.GetString("HaritaHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details:.
        /// </summary>
        public static string Hatadetaylari {
            get {
                return ResourceManager.GetString("Hatadetaylari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooster Crowing.
        /// </summary>
        public static string HorozOtusu {
            get {
                return ResourceManager.GetString("HorozOtusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Loading ....
        /// </summary>
        public static string IcerikYukleniyor {
            get {
                return ResourceManager.GetString("IcerikYukleniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr.
        /// </summary>
        public static string Ikindi {
            get {
                return ResourceManager.GetString("Ikindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Asr: .
        /// </summary>
        public static string Ikindinincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Ikindinincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Time: .
        /// </summary>
        public static string KalanSure {
            get {
                return ResourceManager.GetString("KalanSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Kapat {
            get {
                return ResourceManager.GetString("Kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string KaydetVeKapat {
            get {
                return ResourceManager.GetString("KaydetVeKapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Apply.
        /// </summary>
        public static string KaydetVeUygula {
            get {
                return ResourceManager.GetString("KaydetVeUygula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  times.
        /// </summary>
        public static string Kere {
            get {
                return ResourceManager.GetString("Kere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qibla.
        /// </summary>
        public static string Kible {
            get {
                return ResourceManager.GetString("Kible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qibla Direction.
        /// </summary>
        public static string KibleGostergesi {
            get {
                return ResourceManager.GetString("KibleGostergesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occurred trying to get location.
        /// </summary>
        public static string KonumHatasi {
            get {
                return ResourceManager.GetString("KonumHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Permission to Access the Location.
        /// </summary>
        public static string KonumIzniBaslik {
            get {
                return ResourceManager.GetString("KonumIzniBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For normal operation of the application, you need to give permission to access the Location!.
        /// </summary>
        public static string KonumIzniIcerik {
            get {
                return ResourceManager.GetString("KonumIzniIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services are not enabled on the device. You have to turn on location services first!.
        /// </summary>
        public static string KonumKapali {
            get {
                return ResourceManager.GetString("KonumKapali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Services Off.
        /// </summary>
        public static string KonumKapaliBaslik {
            get {
                return ResourceManager.GetString("KonumKapaliBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string KonumYenileButton {
            get {
                return ResourceManager.GetString("KonumYenileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location and prayer times refreshed successfully.
        /// </summary>
        public static string KonumYenilendi {
            get {
                return ResourceManager.GetString("KonumYenilendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string KoyuTema {
            get {
                return ResourceManager.GetString("KoyuTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birds.
        /// </summary>
        public static string KusCiviltisi {
            get {
                return ResourceManager.GetString("KusCiviltisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyz.
        /// </summary>
        public static string Kyrgyz {
            get {
                return ResourceManager.GetString("Kyrgyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the prayer times from the internet..
        /// </summary>
        public static string NamazVaktiAlmaHatasi {
            get {
                return ResourceManager.GetString("NamazVaktiAlmaHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuhr.
        /// </summary>
        public static string Ogle {
            get {
                return ResourceManager.GetString("Ogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Dhuhr: .
        /// </summary>
        public static string Oglenincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Oglenincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time for Dhuhr: .
        /// </summary>
        public static string Ogleningirmesinekalanvakit {
            get {
                return ResourceManager.GetString("Ogleningirmesinekalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes before.
        /// </summary>
        public static string OnBesDakikaOnceden {
            get {
                return ResourceManager.GetString("OnBesDakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Calendar.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string Radyo {
            get {
                return ResourceManager.GetString("Radyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat.
        /// </summary>
        public static string RadyoFitrat {
            get {
                return ResourceManager.GetString("RadyoFitrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat Facebook Page.
        /// </summary>
        public static string RadyoFitratFaceBook {
            get {
                return ResourceManager.GetString("RadyoFitratFaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat Instagram Page.
        /// </summary>
        public static string RadyoFitratInstagram {
            get {
                return ResourceManager.GetString("RadyoFitratInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat Twitter Page.
        /// </summary>
        public static string RadyoFitratTwitter {
            get {
                return ResourceManager.GetString("RadyoFitratTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection required to play the radio, please check your Internet connection. Alternatively, you can listen to the radio by clicking the &apos;Web Site&apos; link..
        /// </summary>
        public static string RadyoIcinInternet {
            get {
                return ResourceManager.GetString("RadyoIcinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Fajr.
        /// </summary>
        public static string SabahSonu {
            get {
                return ResourceManager.GetString("SabahSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Fajr: .
        /// </summary>
        public static string SabahSonunakalanvakit {
            get {
                return ResourceManager.GetString("SabahSonunakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Sehir {
            get {
                return ResourceManager.GetString("Sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the alarm ringtone for this prayer time.
        /// </summary>
        public static string SesSecAciklama {
            get {
                return ResourceManager.GetString("SesSecAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Test.
        /// </summary>
        public static string SesTesti {
            get {
                return ResourceManager.GetString("SesTesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Encountered a Problem.
        /// </summary>
        public static string SorunCikti {
            get {
                return ResourceManager.GetString("SorunCikti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Social Media Links.
        /// </summary>
        public static string SosyalMedyaBaglantisi {
            get {
                return ResourceManager.GetString("SosyalMedyaBaglantisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Foundation.
        /// </summary>
        public static string SuleymaniyeVakfi {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Foundation Facebook Page.
        /// </summary>
        public static string SuleymaniyeVakfiFacebook {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Foundation Instagram Page.
        /// </summary>
        public static string SuleymaniyeVakfiInstagram {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Calendar.
        /// </summary>
        public static string SuleymaniyeVakfiTakvimi {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiTakvimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Foundation Twitter Page.
        /// </summary>
        public static string SuleymaniyeVakfiTwitter {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Takvim {
            get {
                return ResourceManager.GetString("Takvim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To renew the prayer times, you need to be connected to the internet. Turn on WiFi or Mobile data and click &apos;REFRESH&apos;..
        /// </summary>
        public static string TakvimIcinInternet {
            get {
                return ResourceManager.GetString("TakvimIcinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Required.
        /// </summary>
        public static string TakvimIcinInternetBaslik {
            get {
                return ResourceManager.GetString("TakvimIcinInternetBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Tamam {
            get {
                return ResourceManager.GetString("Tamam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the Test.
        /// </summary>
        public static string TestiDurdur {
            get {
                return ResourceManager.GetString("TestiDurdur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support vibration..
        /// </summary>
        public static string TitremeyiDesteklemiyor {
            get {
                return ResourceManager.GetString("TitremeyiDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate.
        /// </summary>
        public static string TitresimSwitch {
            get {
                return ResourceManager.GetString("TitresimSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyghur.
        /// </summary>
        public static string Uyghur {
            get {
                return ResourceManager.GetString("Uyghur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        public static string UygulamaDili {
            get {
                return ResourceManager.GetString("UygulamaDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the app language.
        /// </summary>
        public static string UygulamaDiliniSecin {
            get {
                return ResourceManager.GetString("UygulamaDiliniSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string UygulamaTema {
            get {
                return ResourceManager.GetString("UygulamaTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the app theme.
        /// </summary>
        public static string UygulamaTemasiniSecin {
            get {
                return ResourceManager.GetString("UygulamaTemasiniSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek.
        /// </summary>
        public static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        public static string Vakti {
            get {
                return ResourceManager.GetString("Vakti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Reminder.
        /// </summary>
        public static string VaktiHatirlatmasi {
            get {
                return ResourceManager.GetString("VaktiHatirlatmasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Web Site.
        /// </summary>
        public static string WebSayfa {
            get {
                return ResourceManager.GetString("WebSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        public static string Yatsi {
            get {
                return ResourceManager.GetString("Yatsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Isha: .
        /// </summary>
        public static string Yatsinincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Yatsinincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed since the end of Isha: .
        /// </summary>
        public static string Yatsininciktigindangecenvakit {
            get {
                return ResourceManager.GetString("Yatsininciktigindangecenvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Isha.
        /// </summary>
        public static string YatsiSonu {
            get {
                return ResourceManager.GetString("YatsiSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Program Schedule.
        /// </summary>
        public static string YayinAkisi {
            get {
                return ResourceManager.GetString("YayinAkisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size: .
        /// </summary>
        public static string YaziBoyutu {
            get {
                return ResourceManager.GetString("YaziBoyutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing.
        /// </summary>
        public static string Yenileniyor {
            get {
                return ResourceManager.GetString("Yenileniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string YukseklikFormatsiz {
            get {
                return ResourceManager.GetString("YukseklikFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On time.
        /// </summary>
        public static string Zamaninda {
            get {
                return ResourceManager.GetString("Zamaninda", resourceCulture);
            }
        }
    }
}
