//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuleymaniyeTakvimi.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuleymaniyeTakvimi.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açı.
        /// </summary>
        public static string Aci {
            get {
                return ResourceManager.GetString("Aci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akşam.
        /// </summary>
        public static string Aksam {
            get {
                return ResourceManager.GetString("Aksam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akşamın çıkması için kalan vakit:.
        /// </summary>
        public static string Aksamincikmasnakalanvakit {
            get {
                return ResourceManager.GetString("Aksamincikmasnakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm çalarken bir sorun oluştu, detaylar.
        /// </summary>
        public static string AlarmHatasi {
            get {
                return ResourceManager.GetString("AlarmHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarmı.
        /// </summary>
        public static string Alarmi {
            get {
                return ResourceManager.GetString("Alarmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm kurarken bir hata oluştu.
        /// </summary>
        public static string Alarmkurarkenhataolustu {
            get {
                return ResourceManager.GetString("Alarmkurarkenhataolustu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Sesi.
        /// </summary>
        public static string AlarmSound {
            get {
                return ResourceManager.GetString("AlarmSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm çal.
        /// </summary>
        public static string AlarmSwitch {
            get {
                return ResourceManager.GetString("AlarmSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Takvim.
        /// </summary>
        public static string AylikTakvim {
            get {
                return ResourceManager.GetString("AylikTakvim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Takvim Başarıyla Yenilendi.
        /// </summary>
        public static string AylikTakvimYenilendi {
            get {
                return ResourceManager.GetString("AylikTakvimYenilendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 dakika önceden.
        /// </summary>
        public static string BesDakikaOnceden {
            get {
                return ResourceManager.GetString("BesDakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildiri Ayarı Devre Dışı.
        /// </summary>
        public static string BildiriDevreDisiBaslik {
            get {
                return ResourceManager.GetString("BildiriDevreDisiBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to için bildiri devre dışı bırakıldı..
        /// </summary>
        public static string BildiriDevreDisiIcerik {
            get {
                return ResourceManager.GetString("BildiriDevreDisiIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildiri Ayarı Etkinleşti.
        /// </summary>
        public static string BildiriEtkinBaslik {
            get {
                return ResourceManager.GetString("BildiriEtkinBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to için bildiri etkinleştirildi..
        /// </summary>
        public static string BildiriEtkinIcerik {
            get {
                return ResourceManager.GetString("BildiriEtkinIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim Göster.
        /// </summary>
        public static string BildirimGosterSwitch {
            get {
                return ResourceManager.GetString("BildirimGosterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatırlatma Zamanı:.
        /// </summary>
        public static string BildirmeZamani {
            get {
                return ResourceManager.GetString("BildirmeZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boylam: {0:G7}.
        /// </summary>
        public static string Boylam {
            get {
                return ResourceManager.GetString("Boylam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boylam.
        /// </summary>
        public static string BoylamFormatsiz {
            get {
                return ResourceManager.GetString("BoylamFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalar Saat.
        /// </summary>
        public static string CalarSaat {
            get {
                return ResourceManager.GetString("CalarSaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Desteklemiyor.
        /// </summary>
        public static string CihazDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazınız titretmeyi desteklemiyor.
        /// </summary>
        public static string CihazTitretmeyiDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazTitretmeyiDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlem: {0:G7}.
        /// </summary>
        public static string Enlem {
            get {
                return ResourceManager.GetString("Enlem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlem.
        /// </summary>
        public static string EnlemFormatsiz {
            get {
                return ResourceManager.GetString("EnlemFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinleştir.
        /// </summary>
        public static string EtkinlestirSwitch {
            get {
                return ResourceManager.GetString("EtkinlestirSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezan Sesi.
        /// </summary>
        public static string EzanSesi {
            get {
                return ResourceManager.GetString("EzanSesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecri Kazibin (Sahurun) girmesi için kalan vakit:.
        /// </summary>
        public static string FecriKazibingirmesinekalanvakit {
            get {
                return ResourceManager.GetString("FecriKazibingirmesinekalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecr-i Kâzip.
        /// </summary>
        public static string FecriKazip {
            get {
                return ResourceManager.GetString("FecriKazip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecr-i Sâdık.
        /// </summary>
        public static string FecriSadik {
            get {
                return ResourceManager.GetString("FecriSadik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecri Sadık (Sahur bitimi) için kalan vakit:.
        /// </summary>
        public static string FecriSadikakalanvakit {
            get {
                return ResourceManager.GetString("FecriSadikakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radyo Fıtrat - Fıtrat&apos;ın Sesi.
        /// </summary>
        public static string FitratinSesi {
            get {
                return ResourceManager.GetString("FitratinSesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        public static string Hakkinda {
            get {
                return ResourceManager.GetString("Hakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haritada Göster.
        /// </summary>
        public static string HaritadaGoster {
            get {
                return ResourceManager.GetString("HaritadaGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haritayı açarken bir sorun oluştu.\nDetaylar:.
        /// </summary>
        public static string HaritaHatasi {
            get {
                return ResourceManager.GetString("HaritaHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata detayları:.
        /// </summary>
        public static string Hatadetaylari {
            get {
                return ResourceManager.GetString("Hatadetaylari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horoz Ötüşü.
        /// </summary>
        public static string HorozOtusu {
            get {
                return ResourceManager.GetString("HorozOtusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik yükleniyor ....
        /// </summary>
        public static string IcerikYukleniyor {
            get {
                return ResourceManager.GetString("IcerikYukleniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkindi.
        /// </summary>
        public static string Ikindi {
            get {
                return ResourceManager.GetString("Ikindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkindinin çıkması için kalan vakit:.
        /// </summary>
        public static string Ikindinincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Ikindinincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string Kapat {
            get {
                return ResourceManager.GetString("Kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıble.
        /// </summary>
        public static string Kible {
            get {
                return ResourceManager.GetString("Kible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıble Göstergesi.
        /// </summary>
        public static string KibleGostergesi {
            get {
                return ResourceManager.GetString("KibleGostergesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konuma erişmeye çalışırken bir sorun oluştu..
        /// </summary>
        public static string KonumHatasi {
            get {
                return ResourceManager.GetString("KonumHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konuma Erişme İzni Yok.
        /// </summary>
        public static string KonumIzniBaslik {
            get {
                return ResourceManager.GetString("KonumIzniBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamanın normal çalışması için Konuma erişme yetkisi vermeniz lazım!.
        /// </summary>
        public static string KonumIzniIcerik {
            get {
                return ResourceManager.GetString("KonumIzniIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazda konum hizmetleri etkin değil. Önce konum hizmetlerini açmanız lazım!.
        /// </summary>
        public static string KonumKapali {
            get {
                return ResourceManager.GetString("KonumKapali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum Hizmetleri Kapalı.
        /// </summary>
        public static string KonumKapaliBaslik {
            get {
                return ResourceManager.GetString("KonumKapaliBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        public static string KonumYenileButton {
            get {
                return ResourceManager.GetString("KonumYenileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum ve vakitler başarıyla yenilendi.
        /// </summary>
        public static string KonumYenilendi {
            get {
                return ResourceManager.GetString("KonumYenilendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuş Cıvıltısı.
        /// </summary>
        public static string KusCiviltisi {
            get {
                return ResourceManager.GetString("KusCiviltisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://suleymaniyetakvimi.com/Include/NamazVakitleri.htm.
        /// </summary>
        public static string NamazVaktiAciklama {
            get {
                return ResourceManager.GetString("NamazVaktiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğle.
        /// </summary>
        public static string Ogle {
            get {
                return ResourceManager.GetString("Ogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğlenin çıkması için kalan vakit:.
        /// </summary>
        public static string Oglenincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Oglenincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğlenin girmesi için kalan vakit:.
        /// </summary>
        public static string Ogleningirmesinekalanvakit {
            get {
                return ResourceManager.GetString("Ogleningirmesinekalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 dakika önceden.
        /// </summary>
        public static string OnBesDakikaOnceden {
            get {
                return ResourceManager.GetString("OnBesDakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süleymaniye Vakfı Takvimi.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radyo.
        /// </summary>
        public static string Radyo {
            get {
                return ResourceManager.GetString("Radyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radyo oynatmak için internet gerekli, lütfen internetin bağlı olduğunu kontrol edin, yada &apos;Web Sayfa&apos; linkine tıklayarak web syfasından dinleyebilirsiniz..
        /// </summary>
        public static string RadyoIcinInternet {
            get {
                return ResourceManager.GetString("RadyoIcinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat Bölgesi: GMT {0}.
        /// </summary>
        public static string SaatBolgesi {
            get {
                return ResourceManager.GetString("SaatBolgesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabah Sonu.
        /// </summary>
        public static string SabahSonu {
            get {
                return ResourceManager.GetString("SabahSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabah Sonu için kalan vakit:.
        /// </summary>
        public static string SabahSonunakalanvakit {
            get {
                return ResourceManager.GetString("SabahSonunakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string Sehir {
            get {
                return ResourceManager.GetString("Sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Testi.
        /// </summary>
        public static string SesTesti {
            get {
                return ResourceManager.GetString("SesTesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir Sorunla Karşılaştık.
        /// </summary>
        public static string SorunCikti {
            get {
                return ResourceManager.GetString("SorunCikti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal medya bağlantılarımız.
        /// </summary>
        public static string SosyalMedyaBaglantisi {
            get {
                return ResourceManager.GetString("SosyalMedyaBaglantisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süleymaniye Vakfı.
        /// </summary>
        public static string SuleymaniyeVakfi {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süleymaniye Vakfı Takvimi.
        /// </summary>
        public static string SuleymaniyeVakfiTakvimi {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiTakvimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim.
        /// </summary>
        public static string Takvim {
            get {
                return ResourceManager.GetString("Takvim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namaz vakitlerini yenilemek için internete bağlı olmanız gerekiyor, WiFi yada Mobil veriyi açın ve &apos;YENİLE&apos; yi tıklayın..
        /// </summary>
        public static string TakvimIcinInternet {
            get {
                return ResourceManager.GetString("TakvimIcinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet Gerekiyor.
        /// </summary>
        public static string TakvimIcinInternetBaslik {
            get {
                return ResourceManager.GetString("TakvimIcinInternetBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string Tamam {
            get {
                return ResourceManager.GetString("Tamam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testi Durdur.
        /// </summary>
        public static string TestiDurdur {
            get {
                return ResourceManager.GetString("TestiDurdur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazınız Titretmeyi Desteklemiyor..
        /// </summary>
        public static string TitremeyiDesteklemiyor {
            get {
                return ResourceManager.GetString("TitremeyiDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titret.
        /// </summary>
        public static string TitresimSwitch {
            get {
                return ResourceManager.GetString("TitresimSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakti:.
        /// </summary>
        public static string Vakti {
            get {
                return ResourceManager.GetString("Vakti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakti Hatırlatması.
        /// </summary>
        public static string VaktiHatirlatmasi {
            get {
                return ResourceManager.GetString("VaktiHatirlatmasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Web Sayfa.
        /// </summary>
        public static string WebSayfa {
            get {
                return ResourceManager.GetString("WebSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatsı.
        /// </summary>
        public static string Yatsi {
            get {
                return ResourceManager.GetString("Yatsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatsının çıkması için kalan vakit:.
        /// </summary>
        public static string Yatsinincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Yatsinincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatsının çıktığından beri geçen vakit:.
        /// </summary>
        public static string Yatsininciktigindangecenvakit {
            get {
                return ResourceManager.GetString("Yatsininciktigindangecenvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatsı Sonu.
        /// </summary>
        public static string YatsiSonu {
            get {
                return ResourceManager.GetString("YatsiSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Yayın Akışı.
        /// </summary>
        public static string YayinAkisi {
            get {
                return ResourceManager.GetString("YayinAkisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenileniyor.
        /// </summary>
        public static string Yenileniyor {
            get {
                return ResourceManager.GetString("Yenileniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükseklik: {0}.
        /// </summary>
        public static string Yukseklik {
            get {
                return ResourceManager.GetString("Yukseklik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükseklik.
        /// </summary>
        public static string YukseklikFormatsiz {
            get {
                return ResourceManager.GetString("YukseklikFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamanında.
        /// </summary>
        public static string Zamaninda {
            get {
                return ResourceManager.GetString("Zamaninda", resourceCulture);
            }
        }
    }
}
